[package]
name = "algoritmer"
version = "0.1.0"
authors = ["Allister Isaiah Harvey <a.i.harvey@icloud.com>"]
edition = "2021"

[features]


[dependencies]
num = "0.4.0"
rand = "0.9.0"
hashbrown = { version = "0.15.0" }


[dev-dependencies]
test-case = "3.0.0"
